# Generated by Django 2.2.4 on 2019-09-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadidate',
            new_name='Candidate',
        ),
    ]
