# Generated by Django 2.2.4 on 2019-09-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190923_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='election',
            name='registered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
